export const GET_STATUS = 'GET_STATUS';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILED = 'GET_STATUS_FAILED';
export const GET_STATUS_DETAILS = 'GET_STATUS_DETAILS';
export const GET_STATUS_DETAILS_SUCCESS = 'GET_STATUS_DETAILS_SUCCESS';
export const GET_STATUS_DETAILS_FAILED = 'GET_STATUS_DETAILS_FAILED';